### ISSUE TITLE
aDMIN commands not working

### ISSUE THREAD

**Issue by paulwalter** [Sheogorath-SI/eggdrop-znc-management#3]
Hello,

The only command that gives some reply is !request

but other admin commands are not working at all!

**Comment by PentSec** [comment]
all commands its 0K! :c 
What line error egg said

**Comment by SISheogorath** [comment]
Problem was solved by add the `+Y`-flag to the User and `+znc`-flag to the channel. (And at least add a hostmask to the user, too)

(Solved in IRC talk)
